# Site settings
title: Marx
email: m.blode@gmail.com
description: > # The classless CSS framework (perfect for Communists).
baseurl: "/marx" # the subpath of your site, e.g. /blog/
url: "http://mblode.github.io/marx" # the base hostname & protocol for your site
twitter_username: mblode
github_username:  mblode

# Build settings
markdown: kramdown

exclude:
  - node_modules
