# Permalinks
permalink:        "/:title"
relative_permalinks: true

# Setup
title:            Marx
description:      The classless CSS framework (perfect for Communists).
url:              http://mblode.github.io
baseurl:          /marx
paginate:         4
author:
  name:           Matthew Blode
  url:            https://twitter.com/mblode
  email:          m.blode@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/mblode/marx

highlighter: pygments
safe: true
lsi: false

sass:
  style: :compressed

exclude: ["node_modules", "gulpfile.js", "package.json", "bower-components", "bower.json"]

navigation:
- text: Home
  url: /
- text: Documentation
  url: /documentation.html
